title:             Live My Life
email:             congvm.it@gmail.com
description:       
author:            congvm.it
# baseurl:           "/catchy-ai-blog"
# url:               "http://blackrockdigital.github.io"

# Social Profiles
# twitter_username:  SBootstrap
github_username:   vocong25
facebook_username: vo.cong25

# Build settings
markdown:          markdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
