title:             Hello World
email:             congvm.it@gmail.com
description:       ""
author:            vocong25
# baseurl:           "/vocong25.github.io"
url:               http://vocong25.github.io

# Social Profiles
# twitter_username:  SBootstrap
github_username:   vocong25
facebook_username: vo.cong25

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
